var express = require('express');
var path = require('path');
var app = express();
var rootPath = path.normalize(__dirname+'/../');
app.use('/',express.static(rootPath + '/app'));
app.use('/bower_components', express.static(rootPath + '/bower_components'));
app.use('/components', express.static(rootPath + '/components'));
app.use('/node_modules', express.static(rootPath + '/node_modules'));
app.listen(8000);
console.log('Listening on port 8000');