var emojiOne = [
    {name: 'grinning', unicode: '1f600',shortname:":grinning:"}, 
    {name: 'grimacing', unicode: '1f62c',shortname:":grimacing:"}, 
    {name: 'smile', unicode: '1f604',shortname:":smile:"}, 
    {name: 'joy', unicode: '1f602',shortname:":joy:"}, 
    {name: 'smiley', unicode: '1f603',shortname:":smiley:"}, 
    {name: 'laughing', unicode: '1f606',shortname:":laughing:"}, 
    {name: 'innocent', unicode: '1f607',shortname:":innocent:"}, 
    {name: 'wink', unicode: '1f609',shortname:":wink:"}, 
    {name: 'disappointed', unicode: '1f61e',shortname:":disappointed:"}, 
    {name: 'worried', unicode: '1f61f',shortname:":worried:"}, 
    {name: 'angry', unicode: '1f620',shortname:":angry:"}, 
    {name: 'confused', unicode: '1f615',shortname:":confused:"}, 
    {name: 'tired_face', unicode: '1f62b',shortname:":tired_face:"}, 
    {name: 'scream', unicode: '1f631',shortname:":scream:"}, 
]